pipeline {
    agent {
        label 'slave'
    }

    stages{
        stage('hostname'){
            steps{
                sh 'hostname'
            }
        }

        stage('server date'){
            steps{
                sh 'date'
            }
        }

        stage('cpu details'){
            steps{
                sh 'lscpu'
            }
        }

        stage('memory usage'){
            steps{
                sh 'free -h'
            }
        }

        stage('disk usage details'){
            steps{
                sh 'df -kh'
            }
        }
    }
    
}
